### ISSUE TITLE
Segmentaiton fault with ISO-2022-JP Subject header 

### ISSUE THREAD

**Issue by yuuki-w** [php/pecl-mail-mailparse#29]
Hi team.

We got a crash after updating mailparse-3.1.5 with ISO-2022-JP Subject.

```
$ php -r 'mailparse_msg_parse_file("minimal.eml");'
Segmentation fault (core dumped)

$ gdb -c core.25737 /usr/bin/php
(gdb) bt
#0  tokenize (header=<optimized out>, tokens=tokens@entry=0x0, ntokens=ntokens@entry=0x7fd5dee010e0, report_errors=report_errors@entry=0) at <stdout>:74
#1  0x00007fd5d0871f17 in php_mailparse_rfc822_tokenize (header=0x7fd5dee8d100 "Subject: \033$B%X%C%@$\"$j\033(B", report_errors=report_errors@entry=0) at php_mailparse_rfc822.re:206
#2  0x00007fd5d0870562 in php_mimepart_process_header (part=0x7fd5dee66500) at /usr/src/debug/php-pecl-mailparse-3.1.5/mailparse-3.1.5/php_mailparse_mime.c:395
#3  0x00007fd5d087100a in php_mimepart_process_line (workpart=0x7fd5dee66500) at /usr/src/debug/php-pecl-mailparse-3.1.5/mailparse-3.1.5/php_mailparse_mime.c:640
#4  php_mimepart_parse (part=part@entry=0x7fd5dee66500, 
    buf=0x7fd5dee80045 "Content-type: text/plain; charset=ISO-2022-JP\r\nContent-transfer-encoding: 7bit\r\nX-source-ip: [127.0.0.1]\r\n\r\n\033$B$*Hh$lMM$G$9!\"%F%9%H%a!<%k$G$9!#\033(B\r\n\r\n\033$B0J>e!\"$h$m$7$/$*4j$$CW$7$^$9!#\033(B\r\n", 
    buf@entry=0x7fd5dee80000 "From: aaa@example.jp\r\nTo: bbb@example.jp\r\nSubject: \033$B%X%C%@$\"$j\033(B\r\nContent-type: text/plain; charset=ISO-2022-JP\r\nContent-transfer-encoding: 7bit\r\nX-source-ip: [127.0.0.1]\r\n\r\n\033$B$*Hh$lMM$G$9!\"%F%9%H"..., bufsize=188)
    at /usr/src/debug/php-pecl-mailparse-3.1.5/mailparse-3.1.5/php_mailparse_mime.c:736
#5  0x00007fd5d086c6db in zif_mailparse_msg_parse_file (execute_data=<optimized out>, return_value=0x7ffd5d199e10) at /usr/src/debug/php-pecl-mailparse-3.1.5/mailparse-3.1.5/mailparse.c:1115
#6  0x000056130826eccb in ZEND_DO_ICALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.3.33/Zend/zend_vm_execute.h:649
#7  execute_ex (ex=0x7fd5dee5e360) at /usr/src/debug/php-7.3.33/Zend/zend_vm_execute.h:55499
#8  0x0000561308272ed3 in zend_execute (op_array=op_array@entry=0x7fd5dee7d2a0, return_value=return_value@entry=0x7ffd5d199ed0) at /usr/src/debug/php-7.3.33/Zend/zend_vm_execute.h:60935
#9  0x00005613081d6626 in zend_eval_stringl (str=str@entry=0x56130a07dda0 "mailparse_msg_parse_file(\"minimal.eml\");", str_len=<optimized out>, retval_ptr=retval_ptr@entry=0x0, string_name=string_name@entry=0x5613082f3114 "Command line code")
    at /usr/src/debug/php-7.3.33/Zend/zend_execute_API.c:1022
#10 0x00005613081d66f9 in zend_eval_stringl_ex (str=str@entry=0x56130a07dda0 "mailparse_msg_parse_file(\"minimal.eml\");", str_len=<optimized out>, retval_ptr=retval_ptr@entry=0x0, string_name=string_name@entry=0x5613082f3114 "Command line code", 
    handle_exceptions=handle_exceptions@entry=1) at /usr/src/debug/php-7.3.33/Zend/zend_execute_API.c:1063
#11 0x00005613081d6769 in zend_eval_string_ex (str=str@entry=0x56130a07dda0 "mailparse_msg_parse_file(\"minimal.eml\");", retval_ptr=retval_ptr@entry=0x0, string_name=string_name@entry=0x5613082f3114 "Command line code", handle_exceptions=handle_exceptions@entry=1)
    at /usr/src/debug/php-7.3.33/Zend/zend_execute_API.c:1074
#12 0x000056130827516b in do_cli (argc=3, argv=0x56130a07dd30) at /usr/src/debug/php-7.3.33/sapi/cli/php_cli.c:1031
#13 0x0000561307fe422c in main (argc=3, argv=0x56130a07dd30) at /usr/src/debug/php-7.3.33/sapi/cli/php_cli.c:1396
```

[here is minimal reproducible eml](https://github.com/php/pecl-mail-mailparse/files/12236249/mailparse_segv_minimal.txt)

It works with mailparse-3.1.4.

**Comment by remicollet** [comment]
Related to c97ee56e25253116bdf37cf7467790081fb01617

@cmb69 any idea welcome

**Comment by remicollet** [comment]
Please try 05339c88160cae8c0fd416b503a7ac2d43d055a6

**Comment by yuuki-w** [comment]
Perfect! It works for me.

**Comment by remicollet** [comment]
3.1.6 is released

**Comment by remicollet** [comment]
Thanks for the feedback
