### ISSUE TITLE
Segmentation fault with UTF-8 encoded X-MS-Iris-MetaData header

### ISSUE THREAD

**Issue by jamesshaw1987** [php/pecl-mail-mailparse#30]
Attempting to parse a received email containing a header of 

```
X-MS-Iris-MetaData: =?utf-8?q?{=22Type=22=3Anull=2C=22Fields=22=3A{=22InstanceId=22=3A=2290232a75aacb417581ef2a67?=
 =?utf-8?q?0087e515=3A2=22=2C=22Market=22=3A=22en-gb=22=2C=22TopicId=22=3A=2220d3416a-aa91-4e58-a5?=
 =?utf-8?q?bc-4a2be2a64934=22=2C=22Timestamp=22=3A=228=2F13=2F2023?= 6:01:40
 AM"}}
 ```
 
 is failing on v3.1.5. 

```
$ php -r 'mailparse_msg_parse_file("mailparse_segfault_example.txt");'
$ gdb /usr/bin/php core-php.5798 
(gdb) bt
#0  tokenize (header=<optimized out>, tokens=0x0, ntokens=0x7f570c455080, report_errors=<optimized out>) at /root/mailparse/<stdout>:74
#1  0x00007f5707a5dcbb in php_mailparse_rfc822_tokenize (
    header=0x7f570c482000 "X-MS-Iris-MetaData: =?utf-8?q?{=22Type=22=3Anull=2C=22Fields=22=3A{=22InstanceId=22=3A=2290232a75aacb417581ef2a67?= =?utf-8?q?0087e515=3A2=22=2C=22Market=22=3A=22en-gb=22=2C=22TopicId=22=3A=2220d3416a"..., report_errors=report_errors@entry=0)
    at /root/mailparse/php_mailparse_rfc822.re:206
#2  0x00007f5707a5c19f in php_mimepart_process_header (part=0x7f570c45e280) at /root/mailparse/php_mailparse_mime.c:395
#3  0x00007f5707a5cbfa in php_mimepart_process_header (part=0x7f570c45e280) at /usr/include/php/20220829/Zend/zend_smart_string.h:75
#4  php_mimepart_process_line (workpart=<optimized out>) at /root/mailparse/php_mailparse_mime.c:647
#5  php_mimepart_parse (part=part@entry=0x7f570c45e280, buf=<optimized out>, 
    buf@entry=0x7f570c47f000 "From: aaa@example.com\r\nTo: bbb@example.com\r\nSubject: \033Test\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Transfer-Encoding: quoted-printable\nX-MS-Iris-MetaData: =?utf-8?q?{=22Type=22=3Anull=2C=22F"..., bufsize=8)
    at /root/mailparse/php_mailparse_mime.c:736
#6  0x00007f5707a587f3 in zif_mailparse_msg_parse_file (execute_data=<optimized out>, return_value=0x7ffcc0ae25c0) at /root/mailparse/mailparse.c:1115
#7  0x00007f570e6bbf85 in xdebug_execute_internal (current_execute_data=0x7f570c412080, return_value=0x7ffcc0ae25c0) at /tmp/pear/temp/xdebug/src/base/base.c:953
#8  0x000055e26993c5ae in execute_ex ()
#9  0x00007f570e6bb490 in xdebug_execute_ex (execute_data=0x7f570c412020) at /tmp/pear/temp/xdebug/src/base/base.c:831
#10 0x000055e26993f265 in zend_execute ()
#11 0x000055e2698bd1b4 in zend_eval_stringl ()
#12 0x000055e2698bd38d in zend_eval_stringl_ex ()
#13 0x000055e2699b4d9c in ?? ()
#14 0x000055e2696fbb46 in ?? ()
#15 0x00007f570ea29d90 in __libc_start_call_main (main=main@entry=0x55e2696fb820, argc=argc@entry=3, argv=argv@entry=0x7ffcc0ae3df8) at ../sysdeps/nptl/libc_start_call_main.h:58
#16 0x00007f570ea29e40 in __libc_start_main_impl (main=0x55e2696fb820, argc=3, argv=0x7ffcc0ae3df8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffcc0ae3de8) at ../csu/libc-start.c:392
#17 0x000055e2696fcbc5 in _start ()
```

Example email: [mailparse_segfault_example.txt](https://github.com/php/pecl-mail-mailparse/files/12344124/mailparse_segfault_example.txt)

Working fine on v3.1.4.

**Comment by remicollet** [comment]
Related to c97ee56e25253116bdf37cf7467790081fb01617

@cmb69 any idea welcome

**Comment by remicollet** [comment]
Pl;ease try 05339c88160cae8c0fd416b503a7ac2d43d055a6

**Comment by remicollet** [comment]
3.1.6 is released
